# Eat Safe, Love

## Notebook Set Up

In [41]:
from pymongo import MongoClient
import pandas as pd
from pprint import pprint

In [42]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [43]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [44]:
# review the collections in our database
print(db.list_collection_names())

['establishments']

In [45]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [46]:
# Find the establishments with a hygiene score of 20
query = {'scores.Hygiene': 20}
results = list(establishments.find(query)) 

# Use count_documents to display the number of documents in the result
count = establishments.count_documents(query)
print(f'There are {count} documents in the result.')

# Display the first document in the results using pprint
print(f'The first document is:')
pprint(results[0])

There are 41 documents in the result.
The first document is:
{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': 0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('67425d648c2340b7aeab7a79'),
 'geocode': {'latitude': Decimal128('50.769705'),
             'longitude': Decimal128('0.27694')},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [47]:
# Convert the result to a Pandas DataFrame
df= pd.json_normalize(results)

# Display the number of rows in the DataFrame
print(f"Number of rows: {len(df)}")

# Display the first 10 rows of the DataFrame
df.head(10)

Number of rows: 41

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,67425d648c2340b7aeab7a79,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,0.27694,50.769705,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,67425d658c2340b7aeab7dfa,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,1.278721,51.857536,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,67425d658c2340b7aeab8104,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,1.15927,51.789429,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,67425d658c2340b7aeab82f2,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,0.10202,50.770885,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,67425d658c2340b7aeab8301,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,0.101446,50.770724,None,0001-01-01T00:00:00,0,None,0,0,0,0
5,67425d658c2340b7aeab8ca0,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,0.736349,51.541448,None,0001-01-01T00:00:00,0,None,0,0,0,0
6,67425d658c2340b7aeab8ec1,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,0.7121671,51.5350065,None,0001-01-01T00:00:00,0,None,0,0,0,0
7,67425d668c2340b7aeaba3ec,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,0.602364,51.591515,None,0001-01-01T00:00:00,0,None,0,0,0,0
8,67425d668c2340b7aeaba830,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,0.146449998021126,51.1859474182129,None,0001-01-01T00:00:00,0,None,0,0,0,0
9,67425d668c2340b7aeabb042,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,0.462307,51.57005,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [48]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query = {'LocalAuthorityName': {'$regex': 'London'}, 'RatingValue': {'$gte': 4}}
results = list(establishments.find(query))

# Use count_documents to display the number of documents in the result
count = establishments.count_documents(query)
print(f'There are {count} documents in the result.')

# Display the first document in the results using pprint
print('The first document is:')
pprint(results[0])

There are 33 documents in the result.
The first document is:
{'AddressLine1': 'Oak Apple Farm Building 103 Sheernes Docks',
 'AddressLine2': 'Sheppy Kent',
 'AddressLine3': '',
 'AddressLine4': '',
 'BusinessName': "Charlie's",
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4627.439467780196,
 'FHRSID': 621707,
 'LocalAuthorityBusinessID': 'PI/000025307',
 'LocalAuthorityCode': '508',
 'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
 'LocalAuthorityName': 'City of London Corporation',
 'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'ME12',
 'RatingDate': '2021-10-18T00:00:00',
 'RatingKey': 'fhrs_4_en-gb',
 'RatingValue': 4,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('67425d658c2340b7aeab9494'),
 'geocode': {'latitude': Decimal128('51.369321'),
             'longitude': Decimal128('0.508551')},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/621707',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 10}}

In [49]:
# Convert the result to a Pandas DataFrame
df_result= pd.json_normalize(results)

# Display the number of rows in the DataFrame
print(f"Number of rows: {len(df_result)}")

# Display the first 10 rows of the DataFrame
df.head(10)

Number of rows: 33

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,67425d648c2340b7aeab7a79,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,0.27694,50.769705,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,67425d658c2340b7aeab7dfa,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,1.278721,51.857536,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,67425d658c2340b7aeab8104,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,1.15927,51.789429,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,67425d658c2340b7aeab82f2,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,0.10202,50.770885,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,67425d658c2340b7aeab8301,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,0.101446,50.770724,None,0001-01-01T00:00:00,0,None,0,0,0,0
5,67425d658c2340b7aeab8ca0,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,0.736349,51.541448,None,0001-01-01T00:00:00,0,None,0,0,0,0
6,67425d658c2340b7aeab8ec1,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,0.7121671,51.5350065,None,0001-01-01T00:00:00,0,None,0,0,0,0
7,67425d668c2340b7aeaba3ec,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,0.602364,51.591515,None,0001-01-01T00:00:00,0,None,0,0,0,0
8,67425d668c2340b7aeaba830,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,0.146449998021126,51.1859474182129,None,0001-01-01T00:00:00,0,None,0,0,0,0
9,67425d668c2340b7aeabb042,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,0.462307,51.57005,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [50]:
query = {"BusinessName": "Penang Flavours"}
fields = {"geocode.longitude": 1, "geocode.latitude": 1, "_id": 0}

check_data = establishments.find(query, fields)


for doc in check_data:
    pprint(doc)

{'geocode': {'latitude': Decimal128('51.4769'),
             'longitude': Decimal128('0.0005')}}

In [56]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

degree_search = 0.01
latitude = 51.4769
longitude = 0.0005

query = {
    "RatingValue": 5, 
    "geocode.latitude": {"$gte": latitude - degree_search, "$lte": latitude + degree_search},
    "geocode.longitude": {"$gte": longitude - degree_search, "$lte": longitude + degree_search}
}

sort = [("scores.Hygiene", 1)]
limit = 5

results = list(establishments.find(query).sort(sort).limit(limit))

# Print the results
for result in results:
    pprint(result)

{'AddressLine1': '64-66 Tranquil Vale',
 'AddressLine2': 'Blackheath',
 'AddressLine3': 'London',
 'AddressLine4': '',
 'BusinessName': 'Pizza Express (Restaurants) Limited',
 'BusinessType': 'Restaurant/Cafe/Canteen',
 'BusinessTypeID': 1,
 'ChangesByServerID': 0,
 'Distance': 4649.312145780472,
 'FHRSID': 255421,
 'LocalAuthorityBusinessID': 'PI/000171887',
 'LocalAuthorityCode': '523',
 'LocalAuthorityEmailAddress': 'david.edwards@lewisham.gov.uk',
 'LocalAuthorityName': 'Lewisham',
 'LocalAuthorityWebSite': 'http://www.lewisham.gov.uk/myservices/business/food-safety/Pages/default.aspx',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'SE3 0BN',
 'RatingDate': '2019-01-21T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': 5,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('67425d688c2340b7aeabde24'),
 'geocode': {'latitude': Decimal128('51.467026'),
             'longitude': Decimal128('0.007387')},
 'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/255421',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 0, 'Structural': 5}}
{'AddressLine1': '45 Montpelier Vale',
 'AddressLine2': 'Blackheath',
 'AddressLine3': 'London',
 'AddressLine4': '',
 'BusinessName': 'Ivy Collection',
 'BusinessType': 'Restaurant/Cafe/Canteen',
 'BusinessTypeID': 1,
 'ChangesByServerID': 0,
 'Distance': 4649.307626651096,
 'FHRSID': 1034864,
 'LocalAuthorityBusinessID': 'PI/000295805',
 'LocalAuthorityCode': '523',
 'LocalAuthorityEmailAddress': 'david.edwards@lewisham.gov.uk',
 'LocalAuthorityName': 'Lewisham',
 'LocalAuthorityWebSite': 'http://www.lewisham.gov.uk/myservices/business/food-safety/Pages/default.aspx',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': '',
 'RatingDate': '2018-01-31T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': 5,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('67425d688c2340b7aeabde20'),
 'geocode': {'latitude': Decimal128('51.4676447852657'),
             'longitude': Decimal128('0.00813059223847337')},
 'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/1034864',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}}
{'AddressLine1': 'Ground Floor',
 'AddressLine2': '15-16 Royal Parade',
 'AddressLine3': 'Blackheath',
 'AddressLine4': 'London',
 'BusinessName': 'Cote',
 'BusinessType': 'Restaurant/Cafe/Canteen',
 'BusinessTypeID': 1,
 'ChangesByServerID': 0,
 'Distance': 4649.318879044527,
 'FHRSID': 499238,
 'LocalAuthorityBusinessID': 'PI/000187131',
 'LocalAuthorityCode': '523',
 'LocalAuthorityEmailAddress': 'david.edwards@lewisham.gov.uk',
 'LocalAuthorityName': 'Lewisham',
 'LocalAuthorityWebSite': 'http://www.lewisham.gov.uk/myservices/business/food-safety/Pages/default.aspx',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'SE3 0TL',
 'RatingDate': '2019-01-21T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': 5,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('67425d688c2340b7aeabde36'),
 'geocode': {'latitude': Decimal128('51.4672587'),
             'longitude': Decimal128('0.0074357')},
 'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/499238',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 0, 'Structural': 5}}
{'AddressLine1': 'Ground Floor',
 'AddressLine2': '15-16 Royal Parade',
 'AddressLine3': 'Blackheath',
 'AddressLine4': 'London',
 'BusinessName': 'Cote Brasserie',
 'BusinessType': 'Restaurant/Cafe/Canteen',
 'BusinessTypeID': 1,
 'ChangesByServerID': 0,
 'Distance': 4649.318879044527,
 'FHRSID': 1341447,
 'LocalAuthorityBusinessID': 'PI/000301917',
 'LocalAuthorityCode': '523',
 'LocalAuthorityEmailAddress': 'david.edwards@lewisham.gov.uk',
 'LocalAuthorityName': 'Lewisham',
 'LocalAuthorityWebSite': 'http://www.lewisham.gov.uk/myservices/business/food-safety/Pages/default.aspx',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'SE3 0TL',
 'RatingDate': '2021-05-24T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': 5,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('67425d688c2340b7aeabde35'),
 'geocode': {'latitude': Decimal128('51.4672587'),
             'longitude': Decimal128('0.0074357')},
 'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/1341447',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 0, 'Structural': 0}}
{'AddressLine1': 'Blackheath High',
 'AddressLine2': '29 Wemyss Road',
 'AddressLine3': 'Blackheath',
 'AddressLine4': 'London',
 'BusinessName': 'Accent Catering Services Ltd',
 'BusinessType': 'School/college/university',
 'BusinessTypeID': 7845,
 'ChangesByServerID': 0,
 'Distance': 4649.213357352781,
 'FHRSID': 937547,
 'LocalAuthorityBusinessID': 'PI/000292516',
 'LocalAuthorityCode': '523',
 'LocalAuthorityEmailAddress': 'david.edwards@lewisham.gov.uk',
 'LocalAuthorityName': 'Lewisham',
 'LocalAuthorityWebSite': 'http://www.lewisham.gov.uk/myservices/business/food-safety/Pages/default.aspx',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': '',
 'RatingDate': '2020-09-23T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': 5,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('67425d688c2340b7aeabdd26'),
 'geocode': {'latitude': Decimal128('51.4671128'),
             'longitude': Decimal128('0.0101793')},
 'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/937547',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}}

In [58]:
# Convert result to Pandas DataFrame
pd_result_rating= pd.json_normalize(results)
pd_result_rating

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,67425d688c2340b7aeabde24,255421,0,PI/000171887,Pizza Express (Restaurants) Limited,Restaurant/Cafe/Canteen,1,64-66 Tranquil Vale,Blackheath,London,...,0.007387,51.467026,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,67425d688c2340b7aeabde20,1034864,0,PI/000295805,Ivy Collection,Restaurant/Cafe/Canteen,1,45 Montpelier Vale,Blackheath,London,...,0.00813059223847337,51.4676447852657,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,67425d688c2340b7aeabde36,499238,0,PI/000187131,Cote,Restaurant/Cafe/Canteen,1,Ground Floor,15-16 Royal Parade,Blackheath,...,0.0074357,51.4672587,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,67425d688c2340b7aeabde35,1341447,0,PI/000301917,Cote Brasserie,Restaurant/Cafe/Canteen,1,Ground Floor,15-16 Royal Parade,Blackheath,...,0.0074357,51.4672587,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,67425d688c2340b7aeabdd26,937547,0,PI/000292516,Accent Catering Services Ltd,School/college/university,7845,Blackheath High,29 Wemyss Road,Blackheath,...,0.0101793,51.4671128,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [61]:
# Create a pipeline that:
# 1. Matches establishments with a hygiene score of 0
match_query = {'$match': {'scores.Hygiene': 0}}

# 2. Groups the matches by Local Authority
group_query = {'$group': {'_id': '$LocalAuthorityName', 'count': {'$sum': 1}}}

# 3. Sorts the matches from highest to lowest
sort_query = {'$sort': {'count': -1}}

pipeline = [match_query, group_query, sort_query]
results = list(establishments.aggregate(pipeline))

# Print the number of documents in the result
print(len(results))

# Print the first 10 results
for result in results[:10]:  
    pprint(result)

55
{'_id': 'Thanet', 'count': 1130}
{'_id': 'Greenwich', 'count': 882}
{'_id': 'Maidstone', 'count': 713}
{'_id': 'Newham', 'count': 711}
{'_id': 'Swale', 'count': 686}
{'_id': 'Chelmsford', 'count': 680}
{'_id': 'Medway', 'count': 672}
{'_id': 'Bexley', 'count': 607}
{'_id': 'Southend-On-Sea', 'count': 586}
{'_id': 'Tendring', 'count': 542}

In [62]:
# Convert the result to a Pandas DataFrame
df = pd.DataFrame(results)

# Display the number of rows in the DataFrame
print(f"Number of rows in the DataFrame: {len(df)}")

# Display the first 10 rows of the DataFrame
print("First 10 rows of the DataFrame:")
df.head(10)

Number of rows in the DataFrame: 55
First 10 rows of the DataFrame:

               _id  count
0           Thanet   1130
1        Greenwich    882
2        Maidstone    713
3           Newham    711
4            Swale    686
5       Chelmsford    680
6           Medway    672
7           Bexley    607
8  Southend-On-Sea    586
9         Tendring    542